name: build & tests & lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
          make build
          make pack_install
      - name: tests & linter
        run: |
          make lint
          make test
      - name: publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTED_ID: ${{ secrets.CC_TEST_REPORTED_ID }}
        with:
          coverageCommand: make test-cov
          debug: true

